# Generated by Django 5.1.4 on 2024-12-18 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_wallet_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
