# Generated by Django 5.1.4 on 2024-12-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_wallet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
