# Generated by Django 5.1.4 on 2024-12-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('BNB', 'Binance Coin'), ('LTC', 'Litecoin')], max_length=10),
        ),
    ]
