# Generated by Django 5.1.4 on 2024-12-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('wallet', 'ticker')},
        ),
    ]
