# Generated by Django 5.1.4 on 2024-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_alter_holding_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['ticker', 'timestamp'], name='portfolios__ticker_fb2897_idx'),
        ),
    ]
